---
ansible_user : cameramodule01
ansible_port : 22
ansible_ssh_pass : '{{ wamv_ansible_sudo_pass }}'
ansible_become_pass : '{{ wamv_ansible_sudo_pass }}'
ansible_python_interpreter : '/usr/bin/python3'
ros_package_name : ros-foxy-ros-base
workspace_path : /home/cameramodule01/robotx_ws
ntp_server: false