---
ros_package_name: ros-galactic-desktop
workspace_path: "{{ansible_env.PWD}}/../robotx_ws"
python_workspace_path: "{{ansible_env.PWD}}/../python_ws"
actions_workspace_path: "{{ansible_env.PWD}}/../actions_ws"
dataset_path: "{{ansible_env.PWD}}/../dataset"
ansible_python_interpreter : "/usr/bin/python3"
ansible_connection: local
ntp_server: true